---
- name: deploy as3 dec
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    uri_method: POST

  vars_files:
    - ../creds/big_creds.yaml

  tasks:

  - name: Create a JIRA issue
    uri:
      url: https://18.130.50.202/mgmt/shared/appsvcs/declare
      user: "{{ bigip_user }}"
      password: "{{ bigip_pass }}"
      method: "{{ uri_method }}"
      body: "{{ lookup('file','config.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no


...
